import type { Metadata } from "next";

export const siteConfig: Metadata = {
  metadataBase: new URL("https://hafiz-subhan-portfolio.vercel.app"),
  title: "Hafiz Subhan | Hire Full-Stack Software Engineer",
  description:
    "Hire Hafiz Subhan, a Full-Stack Software Engineer building production-ready React, Next.js, TypeScript, Python, and FastAPI applications with modern UI and scalable architecture.",
  icons: {
    icon: "/vector.png",
    shortcut: "/vector.png",
    apple: "/vector.png",
  },
  keywords: [
    "hafiz subhan",
    "software engineer portfolio",
    "full-stack software engineer",
    "full stack developer",
    "react developer",
    "next.js developer",
    "typescript developer",
    "python developer",
    "fastapi developer",
    "ai integration engineer",
    "web developer",
    "portfolio",
    "resume",
    "cv",
    "frontend engineer",
    "backend engineer",
    "api development",
    "jwt authentication",
    "rbac",
    "computer vision projects",
    "tailwindcss",
    "hire full-stack developer",
    "hire full-stack software engineer",
    "hire react developer",
    "hire next.js developer",
    "hire typescript developer",
    "hire python developer",
    "hire fastapi developer",
    "remote software engineer for hire",
    "portfolio for job application",
    "ats optimized portfolio",
    "software engineer available for hire",
    "freelance full-stack developer",
    "full-stack developer for startup",
    "google software engineer portfolio",
    "meta software engineer portfolio",
    "amazon software engineer portfolio",
    "microsoft software engineer portfolio",
    "hire me software engineer",
  ] as string[],
  authors: {
    name: "Hafiz Subhan",
    url: "https://hafiz-subhan-portfolio.vercel.app",
  },
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Hafiz Subhan | Hire Full-Stack Software Engineer",
    description:
      "Hire-ready portfolio showcasing React, Next.js, TypeScript, Python, FastAPI, AI integrations, and production-grade software engineering projects.",
    url: "https://hafiz-subhan-portfolio.vercel.app",
    siteName: "Hafiz Subhan Portfolio",
    type: "website",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Hafiz Subhan portfolio social preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Hafiz Subhan | Hire Full-Stack Software Engineer",
    description:
      "Hire-ready Full-Stack Software Engineer: React, Next.js, TypeScript, Python, FastAPI, and AI-integrated web applications.",
    images: ["/twitter-image"],
  },
} as const;

